M48
; DRILL file {KiCad 8.0.4} date 2024-07-26T08:44:17-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-26T08:44:17-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X0.0003Y1.123
X0.0003Y0.0
X0.6903Y1.125
X0.6903Y0.002
M30
