M48
; DRILL file KiCad 10.0.1 date 2026-04-26T15:09:50
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-26T15:09:50-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X5.338Y71.12
X5.338Y65.34
T2
X97.278Y10.6
M30
