M48
; DRILL file {KiCad 8.0.4} date 2024-08-16T16:49:31-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-16T16:49:31-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X0.1178Y0.4855
X0.6408Y1.845
X3.7357Y1.845
X3.8157Y0.4855
T2
X0.1978Y1.3045
M30
